const settingsOptions = [
  {
    id: 1,
    name: "View Your Profile",
    Icon: MdManageAccounts,
    enabled: true,
    color: "#000000",
  },
  {
    id: 2,
    name: "Change Name",
    Icon: MdModeEditOutline,
    enabled: true,
    color: "#000000",
  },
  {
    id: 3,
    name: "Change Profile Picture",
    Icon: VscAccount,
    enabled: true,
    color: "#000000",
  },
  {
    id: 4,
    name: "Change E-mail",
    Icon: TbMailForward,
    enabled: false,
    color: "#000000",
  },
  {
    id: 5,
    name: "Reset Password",
    Icon: MdLockReset,
    enabled: true,
    color: "#000000",
  },
  {
    id: 6,
    name: "change Phone Number",
    Icon: FaPhoneAlt,
    enabled: false,
    color: "#000000",
  },
  {
    id: 7,
    name: "Change Theme",
    Icon: MdInvertColors,
    enabled: true,
    color: "#000000",
  },
  {
    id: 8,
    name: "Download Chat",
    Icon: MdDownloading,
    enabled: true,
    color: "#000000",
  },
  {
    id: 9,
    name: "Generate Automated Link",
    Icon: MdAddLink,
    enabled: false,
    color: "#000000",
  },
  {
    id: 10,
    name: "Clear All Chats",
    Icon: MdClearAll,
    enabled: true,
    color: "#ff8888ff",
  },
  { id: 11, name: "Logout", Icon: MdLogout, enabled: true, color: "#ff8888ff" },
];
